default_theme: arabian_birds
default_format: text
used_codenames:
    0.1.0-beta.2: Apricot
    0.1.1-beta.1: Aquamarine
    0.2.0: Arabian Babbler
    0.2.0-beta.1: Asparagus
    0.2.1: Arabian Green Bee-eater
api:
    enabled: false
    endpoint: ""
    cache_dir: ""
    cache_ttl: ""
